# pragma once

typedef struct {
    int lexical_token;
    char *lexeme;
} lexeme;

#define ID 300
#define IMPORT 301


// KEYWORDS
// #define ABSTRACT 
// #define ALIAS 
// #define ALIGN
// #define ASM
// #define ASSERT
// #define AUTO
// #define BODY
// #define BOOL
// #define BREAK
// #define BYTE
// #define CASE
// #define CAST
// #define CATCH
// #define CDOUBLE
// #define CENT
// #define CFLOAT
// #define CHAR
// #define CLASS
// #define CONST
// #define CONTINUE
// #define CREAL
// #define DCHAR
// #define DEBUG
// #define DEFAULT
// #define DELEGATE
// #define DELETE
// #define DEPRECATED
// #define DO
// #define DOUBLE
// #define ELSE
// #define ENUM
// #define EXPORT
// #define EXTERN
// #define FALSE
// #define FINAL
// #define FINALLY
// #define FLOAT
// #define FOR
// #define FOREACH
// #define FOREACH_REVERSE
// #define FUNCTION
// #define GOTO
// #define IDOUBLE
// #define IF
// #define IFLOAT
// #define IMMUTABLE
// #define IMPORT
// #define IN
// #define INOUT
// #define INT
// #define INTERFACE
// #define INVARIANT
// #define IREAL
// #define IS
// #define LAZY
// #define LONG
// #define MACRO
// #define MIXIN
// #define MODULE
// #define NEW
// #define NOTHROW
// #define NULL
// #define OUT
// #define OVERRIDE
// #define PACKAGE
// #define PRAGMA
// #define PRIVATE
// #define PROTECTED
// #define PUBLIC
// #define PURE
// #define REAL
// #define REF
// #define RETURN
// #define SCOPE
// #define SHARED
// #define SHORT
// #define STATIC
// #define STRUCT
// #define SUPER
// #define SWITCH
// #define SYNCHRONIZED
// #define TEMPLATE
// #define THIS
// #define THROW
// #define TRUE
// #define TRY
// #define TYPEID
// #define TYPEOF
// #define UBYTE
// #define UCENT
// #define UINT
// #define ULONG
// #define UNION
// #define UNITTEST
// #define USHORT
// #define VERSION
// #define VOID
// #define WCHAR
// #define WHILE
// #define WITH
// #define __FILE__
// #define __FILE_FULL_PATH__
// #define __FUNCTION__
// #define __LINE__
// #define __MODULE__
// #define __PRETTY_FUNCTION__
// #define __GSHARED
// #define __PARAMETERS
// #define __RVALUE
// #define __TRAITS
// #define __VECTOR